### ISSUE TITLE
Updating packages

### ISSUE THREAD

**Issue by henricavalcante** [avh4/binwrap#29]
Hello, I found that you guys added on this [commit](https://github.com/avh4/binwrap/commit/15e772e72388503badc83b8c24c51a4ba618247a) a `fs.mkdirSync(path);` line of code but it's causing errors like:

```
error /Users/henricavalcante/contadev/front-end/node_modules/elm-format: Command failed.
Exit code: 1
Command: binwrap-install
Arguments:
Directory: /Users/henricavalcante/contadev/front-end/node_modules/elm-format
Output:
ERR { Error: EEXIST: file already exists, mkdir '/Users/henricavalcante/contadev/front-end/node_modules/elm-format/unpacked_bin'
    at Object.mkdirSync (fs.js:750:3)
    at /Users/henricavalcante/contadev/front-end/node_modules/binwrap/binstall.js:45:8
    at new Promise (<anonymous>)
    at untgz (/Users/henricavalcante/contadev/front-end/node_modules/binwrap/binstall.js:21:10)
    at binstall (/Users/henricavalcante/contadev/front-end/node_modules/binwrap/binstall.js:11:12)
    at install (/Users/henricavalcante/contadev/front-end/node_modules/binwrap/install.js:20:10)
    at Object.install (/Users/henricavalcante/contadev/front-end/node_modules/binwrap/index.js:14:14)
    at Object.<anonymous> (/Users/henricavalcante/contadev/front-end/node_modules/binwrap/bin/binwrap-install:18:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
  errno: -17,
  syscall: 'mkdir',
```

so, can I send a pull request wrapping it on :

```
if (!fs.existsSync(path)) {
   fs.mkdirSync(path);
}
```

Issue related:
https://github.com/avh4/elm-format/issues/602

**Comment by MorganPersson** [comment]
This is fixed by PR #28
