### ISSUE TITLE
Error: No binaries are available for your platform: darwin-arm64

### ISSUE THREAD

**Issue by geofflangenderfer** [avh4/binwrap#62]
is there an alternative to binwrap for arm? Or does anyone have any idea the work involved to add support?

```
npm ERR! node_modules/binwrap/install.js:18
npm ERR!     throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!     ^
npm ERR!
npm ERR! Error: No binaries are available for your platform: darwin-arm64
npm ERR!     at install (node_modules/binwrap/install.js:18:11)
npm ERR!     at Object.install (node_modules/binwrap/index.js:14:14)
npm ERR!     at Object.<anonymous> (node_modules/binwrap/bin/binwrap-install:18:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47

```

**Comment by geofflangenderfer** [comment]
I resolved this by updating dependencies in my project
