### ISSUE TITLE
No binaries are available for: darwin-arm64 (Mac OS Monterey with M1 chip)

### ISSUE THREAD

**Issue by rblnguyen** [avh4/binwrap#63]
npm i binwrap

> elmi-to-json@1.2.0 install /node_modules/elmi-to-json
> binwrap-install

/node_modules/elmi-to-json/node_modules/binwrap/install.js:18
    throw new Error("No binaries are available for your platform: " + buildId);
    ^

Error: No binaries are available for your platform: darwin-arm64
    at install (/node_modules/elmi-to-json/node_modules/binwrap/install.js:18:11)
    at Object.install (/node_modules/elmi-to-json/node_modules/binwrap/index.js:14:14)
    at Object.<anonymous> (/node_modules/elmi-to-json/node_modules/binwrap/bin/binwrap-install:18:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by avh4** [comment]
binwrap can only install binaries that are provided by the package that is using binwrap.  So in this case, this is an issue with [elmi-to-json](https://www.npmjs.com/package/elmi-to-json) which will need to release a new version and provide darwin-arm64 binaries.

**Comment by rblnguyen** [comment]
thx u. Opened an [issue](https://github.com/stoeffel/elmi-to-json/issues/45) with elmi-to-json
